#########################
## Sample Sass Lint File
#########################
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
  # Set the formatter to 'html'
  formatter: html
  # Output file instead of logging results
  output-file: 'linters/sass-lint.html'
  # Raise an error if more than 50 warnings are generated
  max-warnings: 50
# File Options
files:
  include: 'sass/**/*.s+(a|c)ss'
  ignore:
    - 'sass/vendor/**/*.*'
# Rule Configuration
rules:
  force-pseudo-nesting: 2
  no-important: 2
  no-duplicate-properties: 2
  no-url-protocols: 2
  #no-extends: 2
  no-empty-rulesets: 2
  no-misspelled-properties: 2
  no-url-domains: 2
  no-transition-all: 2
  nesting-depth:
    - 2
    - max-depth: 4
  indentation:
    - 1
    - size: tab
